apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "go-web-app-chart.fullname" . }}
  labels:
{{ include "go-web-app-chart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
{{ include "go-web-app-chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
{{ include "go-web-app-chart.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.container.port }}
