apiVersion: v1
kind: Service
metadata:
  name: new-one
  labels:
    app: new-one
spec:
  type: LoadBalancer
  selector:
    app: go-web-app
  ports:
    - port: { { .Values.service.port } }
      targetPort: { { .Values.service.targetPort } }
      protocol: "{{ .Values.service.protocol }}"
